llm_to_schema_map = {
    # --- Infant Details ---
    "Date of Admission": "date",
    "Time baby seen (24 hr clock)": "time_seen",
    "Sex": "sex",
    "DOB": "birth_date",
    "Time of birth (24 hr clock)": "time_birth",
    "Gestation (in weeks)": "gestation_in_weeks",
    "Age (in days)": "baby_age_in_days",
    "Delivery": "delivery_type",
    "Born outside facility?": "born_before_arrival",
    "If yes, where?": "born_where",
    "APGAR Score": "apgar_score",

    # APGAR

    # --- Mother Details ---
    "Age (years)": "mum_age_in_years",
    #"Parity": ["parity_live", "parity_abortions"],
    "Parity": "parity",
    "EDD": "date_estimated_delivery_date",
    "ANC no. of visits": "anc_visits",
    "ANC U/S": "mum_has_anc_ultrasound",
    "Blood group": "blood_group",
    "Rhesus": "rhesus",
    "Anti D": "given_anti_D_medication",
    "VDRL": "mum_had_vdrl",
    "PMTCT status": "mum_pmtct_status",
    "Mother on ARVs": "mum_on_arvs",
    "Hep B": "mum_had_hepatitis_b",
    "Hep B IG given": "mum_given_HBIG_treatment",
    "HTN in pregnancy?": "mum_had_hypertension_in_pregnancy",
    "APH": "mum_had_antepartum_haemorrhage",
    "Diabetes": "mum_had_diabetes",
    "Prolonged 2nd Stage?": "prolonged_labour",

    # --- Vitals ---
    "Temp": "temparature",
    "Resp Rate": "respiratory_rate",
    "Pulse": "pulse_rate",
    "O₂ Sat": "pulse_oximetry",
    "Birth Weight (grams)": "birth_weight",
    "Weight now (grams)": "weight",
    "Head circumference (cm)": "head_circumference",
    "Length (cm)": "length",
    "Blood Pressure": "blood_pressure",

    # Blood pressure

    # --- Symptoms ---
    "Fever": "has_fever",
    "Passed meconium/stool": "passed_meconium",
    "Difficulty breathing": "has_difficulty_breathing",
    "Passed urine in the last 12 hours": "passed_urine",
    "Inability to feed": "has_difficulty_feeding",
    "Convulsions / Twitching": "has_convulsions",
    "Apnoea": "has_apnoea",
    "Reduced / Absent movement": "is_floppy",
    "Bilious Vomiting": "has_vomiting",
    "Bloody stool": "has_diarhoea",
}
{
    "_id": "NAR_63000001_page_2.png",
    "appearance": "sick",
    "capillary_refill_in_seconds": "",
    "chest_indrawing": true,
    "cry": "weak",
    "given_bcg": null,
    "given_bilirubin": null,
    "given_chlorhexidine": true,
    "given_prophylaxis_pmtct": false,
    "given_vitamin_k": true,
    "has_birth_defects": false,
    "has_bulging_fontanelle": false,
    "has_central_cyanosis": false,
    "has_crackles": false,
    "has_good_air_entry": true,
    "has_grunting": false,
    "has_murmur": false,
    "hospital": "7",
    "intercostal_retraction": "severe",
    "is_distended": false,
    "is_irritable": false,
    "jaundice": "none",
    "pallor": "none",
    "prescribed_antibiotics": false,
    "prescribed_caffeine_citrate": false,
    "prescribed_cpap": false,
    "prescribed_feeds": true,
    "prescribed_incubator": true,
    "prescribed_iv_fluids": true,
    "prescribed_kmc": false,
    "prescribed_opv": null,
    "prescribed_oxygen": true,
    "prescribed_phototherapy": false,
    "prescribed_surfactant": false,
    "prescribed_transfusion": false,
    "primary_admission_diagnosis": "asphyxia; ",
    "rbs_measured": true,
    "record_type": "NAR",
    "secondary_admission_diagnosis": "rds; ",
    "skin": "normal",
    "tone": "reduced",
    "umbilicus": "clean",
    "xiphoid_retraction": "mild"
}